### ISSUE TITLE
Atlas

### ISSUE THREAD

**Issue by c-assl** [medialab/portic-storymaps-2021#11]
# Integration

## List view 

- [x] display grid ou flex
- [x] vignettes à génerer pour chaque visualisation

## Lightbox @c-assl 

![Atlas des visualisations](https://user-images.githubusercontent.com/71814474/122034959-52264c80-cdd2-11eb-946e-e3b433973cc8.png)

![Atlas des visualisations (avec lightbox)](https://user-images.githubusercontent.com/71814474/122034965-53f01000-cdd2-11eb-864f-16a9370054b8.png)

**Comment by robindemourat** [comment]
Related commits (forgot to reference the issue):

ef9e4d7682461ae1759830c9f79b30f6891ec85e
b2272bed57a6ea8ea197e5601a3f2ba967556b2e
19600b6a5c697e601f002a18a7c64f6bf26b8856
0d1bba1b23fa10363ba983a2b8c6f6e606eb2534

**Comment by robindemourat** [comment]
Idea : automate snapshots making with a image-based test lib such as [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot] or [react-test-renderer](https://fr.reactjs.org/docs/test-renderer.html#testrenderercreate)
